modLoader = "javafml"
loaderVersion = "[2,)"
issueTrackerURL = "https://github.com/barnabwhy/SmoothMaps/issues"
license = "MIT"

[[mods]]
modId = "smoothmaps"
version = "${version}"
displayName = "SmoothMaps"
authors = "Barnaby"
description = '''
Provides smooth lighting for framed maps, paintings and rails.
'''
logoFile = "assets/smoothmaps/icon.png"

[[dependencies.smoothmaps]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.smoothmaps]]
modId = "minecraft"
type = "required"
versionRange = "[${min_minecraft_version},${max_minecraft_version}]"
ordering = "NONE"
side = "BOTH"


[[mixins]]
config = "smoothmaps.mixins.json"

[[accessTransformers]]
file="META-INF/accesstransformer.cfg"